"""L_mid builder for the multi-level specificity ladder (FINAL_PHASE_PLAN C1).

Upgrades the FI_spec dial from a 2-point contrast to a within-question
dose-response: for questions with m0 in {3..5}, construct a PARTIALLY
disambiguated question text that admits exactly a subset S of the
interpretations (|S| = ceil(m0/2), target always in S):

    level 0:  Q        m_valid = m0            FI_spec = 0
    level 1:  Q_mid    m_valid = |S|           FI_spec = log2(m0/|S|)
    level 2:  Q_target m_valid = 1             FI_spec = log2(m0)

The rewrite is generated by the paraphrase generator model (Phi-4) and only
ACCEPTED when it survives the admits-exactly-S gate:

  (a) judge votes: for EVERY interpretation i, a yes/no judge call "could a
      reader interpret Q_mid as asking Q_i?" must equal (i in S);
  (b) answer-leak guard: no interpretation's answer string appears verbatim
      (casefold) in Q_mid — the question must never carry the solution;
  (c) triviality guard: Q_mid differs from Q and from every Q_i.

Questions where no candidate passes within the attempt budget are marked
`failed` and EXCLUDED from the arm (coverage is reported, mirroring the
rho_F coverage discipline). Generation is seeded + cached via the LLMRequest
machinery, and results are persisted to a parquet keyed (question_id, seed),
so prep and every model chain agree on the exact same L_mid text.

The scoring-gold guardrail is UNTOUCHED: `target_answers` stays fixed across
all three levels (see build_levels.build_spec_levels_multilevel).
"""

from __future__ import annotations

import hashlib
import math
from typing import Sequence

import pandas as pd
from loguru import logger
from pydantic import BaseModel, ConfigDict, Field

from ..data.ambigqa_schemas import AmbigQuestion

_MID_GEN_ATTEMPTS = 4          # candidate rewrites tried before giving up
_JUDGE_VOTES = 3               # self-consistency samples per (candidate, interp)
_MAX_MID_CHARS = 300


class MidQuestion(BaseModel):
    """One persisted L_mid rewrite (accepted or failed) for a question."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    question_id: str
    seed: int
    subset: tuple[int, ...]          # admitted interpretation indices, sorted
    text: str                        # "" when outcome == "failed"
    outcome: str                     # "accepted" | "failed"
    attempts: int
    # Per-interpretation judge majority on the accepted candidate (parallel to
    # interpretation order), for the human-review file. Empty when failed.
    judge_admits: tuple[bool, ...] = Field(default_factory=tuple)


def choose_mid_subset(
    question_id: str, m0: int, target_idx: int, *, seed: int
) -> tuple[int, ...]:
    """Deterministic admitted-subset for L_mid: size ceil(m0/2), contains the
    target, strictly between singleton and full (requires m0 >= 3).

    Non-target members are ranked by sha256(qid::seed::mid::i) — stable across
    processes (no salted hash()), mirroring choose_target_idx.
    """
    if m0 < 3:
        raise ValueError(f"multi-level ladder needs m0 >= 3, got {m0}")
    if not 0 <= target_idx < m0:
        raise ValueError(f"target_idx {target_idx} out of range for m0={m0}")
    size = math.ceil(m0 / 2)
    # ceil(3/2)=2, ceil(4/2)=2, ceil(5/2)=3 — always in [2, m0-1] for m0 in 3..5;
    # for even m0 >= 6 ceil(m0/2)=m0/2 < m0 ✓ (still strictly between).
    others = [i for i in range(m0) if i != target_idx]
    others.sort(key=lambda i: hashlib.sha256(
        f"{question_id}::{seed}::mid::{i}".encode("utf-8")).hexdigest())
    subset = sorted([target_idx] + others[: size - 1])
    return tuple(subset)


def _leak_guard(text: str, q: AmbigQuestion) -> bool:
    """True when NO interpretation's answer appears verbatim in the rewrite."""
    low = text.casefold()
    return not any(
        a.casefold() in low
        for interp in q.interpretations
        for a in interp.answers
        if len(a.strip()) >= 3  # 1-2 char "answers" false-positive on articles
    )


def _triviality_guard(text: str, q: AmbigQuestion) -> bool:
    """True when the rewrite is not just Q or one of the Q_i verbatim."""
    norm = " ".join(text.casefold().replace("?", " ").split())
    seen = {" ".join(q.question.casefold().replace("?", " ").split())}
    for interp in q.interpretations:
        seen.add(" ".join(
            interp.disambiguated_question.casefold().replace("?", " ").split()))
    return bool(norm) and norm not in seen


def _mid_gen_messages(q: AmbigQuestion, subset: Sequence[int]) -> list[dict]:
    admitted = [q.interpretations[i].disambiguated_question for i in subset]
    excluded = [
        interp.disambiguated_question
        for i, interp in enumerate(q.interpretations)
        if i not in set(subset)
    ]
    adm = "\n".join(f"  - {t}" for t in admitted)
    exc = "\n".join(f"  - {t}" for t in excluded)
    user = (
        "An ambiguous question can be read in several ways.\n\n"
        f"Ambiguous question: {q.question}\n\n"
        f"Readings that must REMAIN possible:\n{adm}\n\n"
        f"Readings that must be RULED OUT:\n{exc}\n\n"
        "Write ONE natural English question that a reader could still interpret "
        "as any of the remaining readings, but NOT as any ruled-out reading. "
        "Keep it a single question. Do not mention, hint at, or enumerate "
        "answers. Output only the question text."
    )
    return [
        {"role": "system",
         "content": "You rewrite questions to control exactly how ambiguous "
                    "they are. You output only the rewritten question."},
        {"role": "user", "content": user},
    ]


def _judge_messages(mid_text: str, reading: str) -> list[dict]:
    return [
        {"role": "system",
         "content": "You judge question interpretations. Answer with exactly "
                    "one word: yes or no."},
        {"role": "user",
         "content": (f"Question A: {mid_text}\n"
                     f"Reading B: {reading}\n\n"
                     "Could a reasonable reader interpret question A as asking "
                     "reading B? Answer yes or no.")},
    ]


def _seed_for(question_id: str, tag: str, k: int, seed: int) -> int:
    digest = hashlib.sha256(
        f"{question_id}::{seed}::{tag}::{k}".encode("utf-8")).hexdigest()
    return int(digest[:8], 16)


def generate_mid_question(
    q: AmbigQuestion, *, seed: int, config
) -> MidQuestion:
    """Generate + gate one L_mid rewrite (seeded, cached at the LLM layer)."""
    from ..models.registry import get_client
    from ..models.schemas import LLMRequest

    pcfg = config.paraphrases
    client = get_client(pcfg.generator_model, config)
    entry = config.models[pcfg.generator_model]
    m0 = q.m0()
    from .build_levels import choose_target_idx
    target_idx = choose_target_idx(q.id, m0, seed=seed)
    subset = choose_mid_subset(q.id, m0, target_idx, seed=seed)
    subset_set = set(subset)

    def _ask(messages, tag, k, max_tokens, temperature) -> str:
        req = LLMRequest(
            provider=entry.provider, model_id=entry.model_id,
            messages=messages, temperature=temperature, top_p=1.0,
            max_tokens=max_tokens, seed=_seed_for(q.id, tag, k, seed),
            purpose=f"midlevel::{tag}",
        )
        return (client.complete(req).text or "").strip()

    for attempt in range(_MID_GEN_ATTEMPTS):
        raw = _ask(_mid_gen_messages(q, subset), "gen", attempt,
                   max_tokens=96, temperature=pcfg.generator_temperature)
        text = raw.splitlines()[0].strip().strip('"').strip() if raw else ""
        if not text or len(text) > _MAX_MID_CHARS:
            continue
        if not (_leak_guard(text, q) and _triviality_guard(text, q)):
            continue
        votes: list[bool] = []
        ok = True
        for i, interp in enumerate(q.interpretations):
            yes = 0
            for v in range(_JUDGE_VOTES):
                ans = _ask(_judge_messages(text, interp.disambiguated_question),
                           f"judge{attempt}::{i}", v, max_tokens=4,
                           temperature=0.2).casefold()
                yes += int(ans.startswith("y"))
            admits = yes * 2 > _JUDGE_VOTES
            votes.append(admits)
            if admits != (i in subset_set):
                ok = False   # keep voting to fill the review record
        if ok:
            return MidQuestion(
                question_id=q.id, seed=seed, subset=subset, text=text,
                outcome="accepted", attempts=attempt + 1,
                judge_admits=tuple(votes),
            )
        logger.debug("mid candidate rejected qid={} attempt={} votes={} subset={}",
                     q.id, attempt, votes, subset)
    logger.warning("no L_mid rewrite passed the gate for qid={} ({} attempts)",
                   q.id, _MID_GEN_ATTEMPTS)
    return MidQuestion(question_id=q.id, seed=seed, subset=subset, text="",
                       outcome="failed", attempts=_MID_GEN_ATTEMPTS)


# --------------------------------------------------------------------------- #
# Persistence (append-atomic parquet, same pattern as the paraphrase cache)   #
# --------------------------------------------------------------------------- #


def load_mid_cache(parquet_path) -> dict[str, MidQuestion]:
    """question_id -> MidQuestion for every persisted row (any outcome)."""
    out: dict[str, MidQuestion] = {}
    if not parquet_path.exists():
        return out
    try:
        df = pd.read_parquet(parquet_path)
    except Exception as exc:  # noqa: BLE001
        logger.warning("could not read {} ({}); regenerating", parquet_path, exc)
        return out
    for _, r in df.iterrows():
        out[str(r["question_id"])] = MidQuestion(
            question_id=str(r["question_id"]), seed=int(r["seed"]),
            subset=tuple(int(i) for i in r["subset"]),
            text=str(r["text"]), outcome=str(r["outcome"]),
            attempts=int(r["attempts"]),
            judge_admits=tuple(bool(b) for b in r["judge_admits"]),
        )
    return out


def append_mid_cache(parquet_path, mid: MidQuestion) -> None:
    """Persist one result immediately (atomic replace) — walltime-kill safe."""
    row = {
        "question_id": mid.question_id, "seed": mid.seed,
        "subset": list(mid.subset), "text": mid.text, "outcome": mid.outcome,
        "attempts": mid.attempts, "judge_admits": list(mid.judge_admits),
    }
    df_new = pd.DataFrame([row])
    if parquet_path.exists():
        try:
            df_new = pd.concat([pd.read_parquet(parquet_path), df_new],
                               ignore_index=True)
        except Exception:  # noqa: BLE001
            pass
    parquet_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = parquet_path.with_suffix(parquet_path.suffix + ".tmp")
    df_new.to_parquet(tmp, index=False)
    tmp.replace(parquet_path)
