"""PromptSensitivityFI — research demo app (Streamlit).

Audience: researchers. Presents the project, the metric findings (v3 full run),
the data, and an interactive prompt-feedback panel backed by the trained
4-head probe bundles.

Modularity contract:
  * every artifact path lives in PATHS below — move/rename data, edit one dict;
  * every section loads through a cached loader keyed on file mtime and
    degrades to an instruction box when its artifact is missing;
  * figures are the canonical PNGs from `figures/` (regenerated by the
    analysis scripts), never recomputed here.

Run:   uv run streamlit run app/streamlit_app.py
Share: ngrok http 8501   (see app/README.md)
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from prompt_sensitivity.feedback.heads import (  # noqa: E402
    FeedbackModel, build_features, compose_feedback, head_labels,
)

MODELS = {
    "qwen_2_5_7b": "Qwen-2.5-7B",
    "llama_3_1_8b": "Llama-3.1-8B",
    "mistral_7b_v03": "Mistral-7B-v0.3",
}
PATHS = {
    "metrics": "data/specificity_v3_{m}.parquet",
    "features": "data/hidden_states_{m}.parquet",
    "bundle": "data/feedback_model_{m}.joblib",
    "verification": "data/feedback_verification.parquet",
    "table_json": "figures/v3_table.json",
    "fig_bars": "figures/v3_multimodel_bars.png",
    "fig_curves": "figures/v3_fi_curves_graded.png",
    "fig_fiout": "figures/v3_fi_out_decomposition.png",
    "fig_families": "figures/v3_metric_families.png",
    "fig_reportcard": "figures/v3_metric_report_card.png",
    "fig_axes": "figures/v3_three_axes_dataset.png",
    "fig_probes": "figures/v3_probe_layers.png",
    "fig_fispec": "figures/v3_fispec_vs_fiin.png",
}


def p(key: str, m: str | None = None) -> Path:
    return REPO / PATHS[key].format(m=m)


def _mtime(path: Path) -> float:
    return path.stat().st_mtime if path.exists() else -1.0


def missing(path: Path, hint: str) -> bool:
    if not path.exists():
        st.warning(f"`{path.relative_to(REPO)}` not found — {hint}")
        return True
    return False


@st.cache_data(show_spinner=False)
def load_metrics(m: str, _mt: float) -> pd.DataFrame:
    df = pd.read_parquet(p("metrics", m))
    df["question_id"] = df.question_id.astype(str)
    return df


@st.cache_resource(show_spinner="Loading TBG features (~100 MB)…")
def load_feature_matrix(m: str, _mt: float):
    hs = pd.read_parquet(p("features", m))
    X, meta = build_features(hs)
    return X, meta


@st.cache_resource(show_spinner=False)
def load_bundle(m: str, _mt: float) -> FeedbackModel:
    return FeedbackModel.load(p("bundle", m))


def img(key: str, caption: str = ""):
    path = p(key)
    if path.exists():
        st.image(str(path), caption=caption or None)
    else:
        st.info(f"figure `{path.name}` missing — regenerate via the analysis scripts")


def gauge_row(g: dict[str, float]):
    cols = st.columns(4)
    spec = [("vagueness", "Vagueness", "P(ambiguous)"),
            ("reliability", "Reliability", "E[P(correct)]"),
            ("dispersion", "Dispersion", "P(high H_sem)"),
            ("fragility", "Fragility ⚠exp.", "P(high ρ_F)")]
    for col, (k, label, sub) in zip(cols, spec):
        v = g.get(k)
        with col:
            st.metric(label, f"{v:.2f}" if v is not None else "–", help=sub)
            if v is not None:
                st.progress(min(max(float(v), 0.0), 1.0))


# --------------------------------------------------------------------------- #
st.set_page_config(page_title="PromptSensitivityFI", page_icon="📏", layout="wide")

with st.sidebar:
    st.title("📏 PromptSensitivityFI")
    st.caption("Functional Information for prompts — KIT seminar (Thanos Drossos)")
    model_key = st.selectbox("Target model", list(MODELS), format_func=MODELS.get)
    st.divider()
    st.subheader("Data status")
    for key, needs_m in [("metrics", True), ("features", True), ("bundle", True),
                         ("verification", False)]:
        path = p(key, model_key) if needs_m else p(key)
        ok = path.exists()
        ts = pd.Timestamp(path.stat().st_mtime, unit="s").strftime("%Y-%m-%d %H:%M") if ok else "—"
        st.caption(("✅" if ok else "❌") + f" `{path.name}` {ts}")
    if st.button("Reload data (clear caches)"):
        st.cache_data.clear()
        st.cache_resource.clear()
        st.rerun()

tab_over, tab_metrics, tab_data, tab_try, tab_verif = st.tabs(
    ["Overview", "Metrics & findings", "Data explorer", "🧪 Try the model", "Model verification"])

# ------------------------------------------------------------ Overview
with tab_over:
    st.header("Functional Information as a prompt-sensitivity metric")
    c1, c2 = st.columns([3, 2])
    with c1:
        st.markdown("""
**Question.** How much does a prompt's *phrasing* determine whether an LLM can
answer — and can we measure that in bits?

**Construction (Szostak/Hazen functional information, translated to prompts).**
For a question `q`, build a universe `U_q` of meaning-preserving paraphrases
(8 personas → bidirectional-NLI filter → multi-gold answer-preservation filter),
score each paraphrase's *function* `F(x) = P(correct | x)` (estimated from k=10
samples, NLI-judged against fixed gold answers), and read:
""")
        st.latex(r"FI_{in}(q,k) = -\log_2\frac{|\{x \in U_q : F(x)\ge k\}|}{|U_q|}")
        st.markdown("""
**Experiment (v3 full run).** 149 AmbigQA questions × 2 *specificity levels*
(L0 = the ambiguous question, L1 = one disambiguated rewrite; gold answer and
evidence identical across levels — specificity is the *only* manipulated
variable) × 3 open-weight models (Qwen-2.5-7B, Llama-3.1-8B, Mistral-7B),
N=10 paraphrases × k=10 samples per cell, on bwUniCluster A100s.

**Headline.** Every hypothesis holds in every model — adding normative
specificity (FI_spec: 0 → 1.43 bits) raises accuracy, lowers input-space
sensitivity, and concentrates the output distribution:
""")
        tj = p("table_json")
        if not missing(tj, "run the v3 analysis to regenerate figures/v3_table.json"):
            t = pd.read_json(tj)
            show = t[["model", "d_acc", "p_acc", "d_aufi_g", "p_aufi_g", "d_h", "p_h"]].rename(
                columns={"d_acc": "Δ accuracy", "p_acc": "p", "d_aufi_g": "Δ AUFI (graded)",
                         "p_aufi_g": "p ", "d_h": "Δ H_sem", "p_h": "p  "})
            st.dataframe(show.style.format(precision=3), hide_index=True)
        st.caption("Paired per-question deltas (L1−L0), Wilcoxon signed-rank, n=149 "
                   "(1 question excluded: singleton paraphrase universe).")
    with c2:
        img("fig_curves", "Graded FI_in(k) curves: disambiguation lowers the whole curve "
                          "(mean gap 0.79–0.87 bits; CI bands separate at every k>0).")
        img("fig_bars")

# ------------------------------------------------------------ Metrics
with tab_metrics:
    st.header("The metric space has three orthogonal dimensions")
    st.markdown("""
We computed 14 candidate metrics per (question, level, model) cell and measured
their within-level correlation structure. They collapse into **three empirical
families plus a dataset-side axis** — so "prompt sensitivity" is not one number:

| Axis | Representative | Family members (within-level ρ to rep.) |
|---|---|---|
| **1 — Ability** | FI_in(k) curve + accuracy | AUFI (≡ accuracy, ρ=−1.00 → appendix), ΔFI premium (.51) |
| **2 — Formulation sensitivity** | **ρ_F (functional ICC)** | ρ_u/Cox (.67 — convergent validity) |
| **3 — Output dispersion** | H_sem (+ FI_out_fixed reading) | S_τ (.94), TVD (.91), \\|A_q\\| (.91), var-ratio (.75), Var[FI_out] (.70), **POSIX (.60)** |
| Dial (dataset-side) | FI_spec = log₂(m₀/m_valid) | ESS_in (⊥ everything) |
""")
    st.latex(r"\rho_F=\frac{MS_{between}-MS_{within}}{MS_{between}+(k{-}1)\,MS_{within}}"
             r"\quad\text{(share of success variance caused by phrasing choice)}")
    st.markdown("""
Key validations: **AUFI ≡ accuracy** (Spearman −1.000 exact under binary F —
why the scalar is demoted and the *curve* is the deliverable); **ρ_F** is
orthogonal to ability (.08) *and* dispersion (.03), agrees with the
embedding-based ρ_u (.67) across a completely different measurement channel,
and is stable when the sample budget doubles (k10↔k20 Spearman .81–.95) while
models genuinely disagree on it (cross-model ~.3) — a **(question × model)
trait**. Every literature metric we measured (POSIX, Errica S_τ/1−TVD, ρ_u)
lands in axes 1 or 3.
""")
    a, b = st.columns(2)
    with a:
        img("fig_families", "Within-level Spearman over 6 blocks (3 models × 2 levels).")
        img("fig_fispec", "FI_spec vs FI_in: coupled in direction, decoupled in magnitude.")
    with b:
        img("fig_reportcard", "Candidate report card + §7.7 x* geometry (H1 confirmed, p≤1e-13 ×3).")
        img("fig_axes", "Every measurable cell in the 3-metric space.")
        img("fig_fiout", "FI_out on the fixed capacity yardstick (calibration fingerprints).")

# ------------------------------------------------------------ Data explorer
with tab_data:
    st.header("Data explorer — one question end to end")
    mpath = p("metrics", model_key)
    if not missing(mpath, "pull/produce the v3 metrics parquet first"):
        df = load_metrics(model_key, _mtime(mpath))
        qids = sorted(df.question_id.unique())
        qid = st.selectbox(f"Question ({len(qids)} in v3)", qids,
                           format_func=lambda q: f"{q} — "
                           + df[(df.question_id == q) & (df.spec_level == 0)].question_text.iloc[0][:80])
        cell = df[df.question_id == qid].sort_values("spec_level")
        cols = st.columns(2)
        for col, (_, row) in zip(cols, cell.iterrows()):
            with col:
                lvl = int(row.spec_level)
                st.subheader(f"L{lvl} — {'ambiguous' if lvl == 0 else 'disambiguated'}")
                st.markdown(f"> {row.question_text}")
                st.caption(f"m₀={int(row.m0)} interpretations · m_valid={int(row.m_valid)} · "
                           f"FI_spec={row.fi_spec:.2f} bits · gold fixed across levels")
                raw_fg = row.f_graded_per_paraphrase
                fg = list(raw_fg) if raw_fg is not None and np.size(raw_fg) else []
                stats = {
                    "accuracy (graded)": row.f_graded_mean,
                    "AUFI_in graded (bits)": row.aufi_in_graded,
                    "ρ_F": row.get("rho_f", float("nan")),
                    "ΔFI premium (bits)": row.get("fi_premium", float("nan")),
                    "H_sem (bits)": row.h_sem_mean,
                    "FI_out_fixed (bits)": row.get("fi_out_fixed",
                                                   np.log2(max(row.m0, 1)) - row.h_sem_mean),
                }
                st.dataframe(pd.DataFrame(stats, index=["value"]).T.style.format("{:.3f}"),
                             use_container_width=True)
                if fg:
                    st.caption("per-paraphrase F(x) = P(correct|x), k=10 samples")
                    st.bar_chart(pd.Series(fg, name="F(x)"), height=140)

# ------------------------------------------------------------ Try the model
with tab_try:
    st.header("🧪 Prompt feedback — the deliverable")
    st.markdown("""
Four **linear probes on the target model's own hidden state** at the last
prompt token (the state it would generate from), isotonic-calibrated, one per
metric axis. One forward pass → four gauges → feedback. *Trained on the v3
uniform-evidence prompts; grouped-OOF verified (see the Verification tab).*
""")
    bpath = p("bundle", model_key)
    if not missing(bpath, "train bundles: `python -m prompt_sensitivity.scripts.train_prompt_feedback`"):
        fm = load_bundle(model_key, _mtime(bpath))
        mode = st.radio("Mode", ["Dataset prompts (instant, in-distribution)",
                                 "Custom prompt (needs the LLM — GPU/cluster)"],
                        horizontal=True)
        if mode.startswith("Dataset"):
            fpath = p("features", model_key)
            if not missing(fpath, "pull the hidden-state dump for this model"):
                X, meta = load_feature_matrix(model_key, _mtime(fpath))
                labels = head_labels(meta, load_metrics(model_key, _mtime(p("metrics", model_key))))
                c1, c2 = st.columns([1, 3])
                with c1:
                    if st.button("🎲 Sample a random prompt", use_container_width=True):
                        st.session_state["try_idx"] = int(np.random.default_rng().integers(len(meta)))
                    idx = int(st.session_state.get("try_idx", 0))
                    idx = st.number_input("…or row index", 0, len(meta) - 1, idx)
                with c2:
                    st.markdown(f"**Prompt:**  \n> {meta.paraphrase.iloc[idx]}")
                g = fm.gauges(X[idx:idx + 1]).iloc[0].to_dict()
                gauge_row(g)
                st.subheader("Feedback")
                for msg in compose_feedback(g):
                    st.markdown(f"- {msg}")
                with st.expander("Reveal ground truth for this prompt"):
                    lab = labels.iloc[idx]
                    st.markdown(
                        f"true level: **L{int(lab.spec_level)}** "
                        f"({'ambiguous' if lab.spec_level == 0 else 'disambiguated'}) · "
                        f"true F(x): **{lab.reliability:.2f}** · "
                        f"cell H_sem: **{lab.dispersion:.2f}** bits · "
                        + (f"cell ρ_F: **{lab.fragility:.2f}**" if np.isfinite(lab.fragility)
                           else "cell ρ_F: n/a (no variance)"))
        else:
            import torch
            cuda = torch.cuda.is_available()
            if cuda:
                vram_gb = torch.cuda.get_device_properties(0).total_memory / 1e9
                if vram_gb < 12:
                    os.environ["PSF_4BIT"] = "1"       # 7B NF4 fits a 6 GB RTX 2060
                    dev_note = (f"local GPU ({torch.cuda.get_device_name(0)}, "
                                f"{vram_gb:.0f} GB) — 4-bit NF4, ~5–15 s per analysis")
                else:
                    dev_note = f"local GPU ({torch.cuda.get_device_name(0)}) — bf16"
            else:
                os.environ["PSF_DEVICE"] = "cpu"
                dev_note = ("CPU (bf16) — needs ~15 GB free RAM and 30–90 s per "
                            "analysis; close other applications first")
            st.info(f"This mode embeds your prompt with the ACTUAL target model "
                    f"(one forward pass). Runs entirely on this machine: {dev_note}. "
                    "First use loads (and completes the download of) the weights.")
            st.caption("⚠ Two honesty notes: (1) heads were trained on prompts that "
                       "carry an evidence context block — a bare prompt is somewhat "
                       "off-distribution; (2) 4-bit quantization perturbs hidden "
                       "states slightly relative to the bf16 training features.")
            prompt = st.text_area("Your prompt", placeholder="Who has the most wins in history?")
            if st.button("Analyze") and prompt.strip():
                try:
                    with st.spinner(f"Embedding with {MODELS[model_key]} ({dev_note.split(' — ')[0]})… "
                                    "first run loads the model, later runs are fast"):
                        from prompt_sensitivity.config import load_config
                        from prompt_sensitivity.models.registry import get_client
                        client = get_client(model_key, load_config())
                        msgs = [[{"role": "system",
                                  "content": "You are a precise question answering assistant. "
                                             "Answer with a short factual answer."},
                                 {"role": "user", "content": prompt.strip()}]]
                        arr, _ = client.chat_hidden_states(msgs, layer_fracs=fm.layer_fracs)
                    g = fm.gauges(arr.reshape(1, -1).astype(np.float32)).iloc[0].to_dict()
                    gauge_row(g)
                    st.subheader("Feedback")
                    for msg in compose_feedback(g):
                        st.markdown(f"- {msg}")
                except Exception as exc:  # noqa: BLE001 — surface, don't crash the app
                    st.error(f"Could not run the target model here: {exc}")
                    st.markdown("Fixes: free RAM/VRAM and retry; ensure the CUDA torch "
                                "build is installed (`uv sync --extra app --extra dev`); "
                                "or run the app on the cluster.")

# ------------------------------------------------------------ Verification
with tab_verif:
    st.header("Model verification (question-grouped out-of-fold)")
    vpath = p("verification")
    if not missing(vpath, "train bundles to produce the verification table"):
        ver = pd.read_parquet(vpath)
        st.dataframe(ver.style.format(precision=3), hide_index=True, use_container_width=True)
        st.markdown("""
Reading: **vagueness** 0.85–0.87 AUROC (flip-control ≈ .5, beats the length
baseline .755) · **reliability** OOF Spearman .41–.52, cross-fitted ECE .06–.08 ·
**dispersion** 0.69–0.79 (controls ≈ .5) · **fragility** ≈ controls — shipped
with an explicit *experimental* flag: the k=20 arm showed its per-prompt
weakness is genuine signal scarcity, not label noise.

Controls: *flip* = invert a random half of questions' labels (the meaningful
null for within-question labels); *permuted* = shuffle label patterns between
questions; *length* = predict from prompt length alone. Splits never put
paraphrases of one question on both sides of a fold.
""")
        img("fig_probes", "Earlier per-layer probe profiles (single-layer heads).")
    st.caption("Known limits: single dataset (AmbigQA) — cross-dataset arm is future "
               "work; per-model bundles; live custom prompts are off-distribution.")

st.sidebar.divider()
st.sidebar.caption(f"repo: {REPO.name} · python {sys.version.split()[0]} · "
                   f"cwd-independent paths ✓ · PID {os.getpid()}")
